language: java
jdk:
    - oraclejdk8
node_js: "0.10"
install:
    - sudo apt-get update -qq
    - sudo apt-get install -y ant
    - npm -g install bower
    - npm -g install grunt-cli 
    - npm -g install pm2 
    - npm install
script:
    - npm test
services:
  - mongodb
  - redis-server
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - pm2 start test-server.js
  - sleep 5